numero = int(input("Digite um némro para ver sua tabuada de 0 à 10: "))
print("-" * 13)
print(f"{numero:2} x  1 = {numero * 1:2}")
print(f"{numero:2} x  2 = {numero * 2:2}")
print(f"{numero:2} x  3 = {numero * 3:2}")
print(f"{numero:2} x  4 = {numero * 4:2}")
print(f"{numero:2} x  5 = {numero * 5:2}")
print(f"{numero:2} x  6 = {numero * 6:2}")
print(f"{numero:2} x  7 = {numero * 7:2}")
print(f"{numero:2} x  8 = {numero * 8:2}")
print(f"{numero:2} x  9 = {numero * 9:2}")
print(f"{numero:2} x 10 = {numero *10:2}")
print("-" * 13)